api_url: "http://localhost:5000/api/logs"
interval: 10

log_candidates:
  - "/var/log/auth.log"
  - "/var/log/secure"
  - "/var/log/syslog"

windows_log: "Security"

retry_attempts: 3
retry_delay: 2

use_realtime_monitoring: true
